# Parallel Process Testing Support for boost.ut
# Provides true parallel multiprocess testing using shell background processes
# Replaces the broken NetworkFixtureTest.cmake pipeline approach

# Function to add a parallel process test with shell script generation
function(ut_add_parallel_process_test)
  set(options PARALLEL SEQUENTIAL)
  set(oneValueArgs NAME TIMEOUT WORKING_DIRECTORY SHELL)
  set(multiValueArgs TARGETS ENVIRONMENT)
  
  cmake_parse_arguments(PP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  
  # Validate required parameters
  if(NOT PP_NAME)
    message(FATAL_ERROR "ut_add_parallel_process_test: NAME is required")
  endif()
  
  if(NOT PP_TARGETS)
    message(FATAL_ERROR "ut_add_parallel_process_test: TARGETS is required")
  endif()
  
  # Set defaults
  if(NOT PP_TIMEOUT)
    set(PP_TIMEOUT 30)
  endif()
  
  if(NOT PP_WORKING_DIRECTORY)
    set(PP_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
  
  if(NOT PP_SHELL)
    set(PP_SHELL "/bin/bash")
  endif()
  
  # Default to parallel execution
  if(NOT PP_SEQUENTIAL AND NOT PP_PARALLEL)
    set(PP_PARALLEL TRUE)
  endif()
  
  # Parse TARGETS - expected format: "target1 args1" "target2 args2" ...
  set(PROCESSES "")
  foreach(target_spec ${PP_TARGETS})
    # Split on first space to separate target from arguments
    string(FIND "${target_spec}" " " first_space)
    if(first_space GREATER -1)
      string(SUBSTRING "${target_spec}" 0 ${first_space} target_name)
      math(EXPR args_start "${first_space} + 1")
      string(SUBSTRING "${target_spec}" ${args_start} -1 target_args)
    else()
      set(target_name "${target_spec}")
      set(target_args "")
    endif()
    
    # Resolve target to executable path if it's a CMake target
    if(TARGET ${target_name})
      set(target_executable "$<TARGET_FILE:${target_name}>")
    else()
      set(target_executable "${target_name}")
    endif()
    
    list(APPEND PROCESSES "${target_executable}|${target_args}")
  endforeach()
  
  # Generate the shell script
  set(SCRIPT_PATH "${CMAKE_CURRENT_BINARY_DIR}/${PP_NAME}_runner.sh")
  
  set(SCRIPT_CONTENT "#!/bin/bash
# Auto-generated parallel process test runner for ${PP_NAME}
# Generated by ut_add_parallel_process_test

set -e  # Exit on any error
set -o pipefail  # Catch pipeline failures

# Test configuration
TEST_NAME=\"${PP_NAME}\"
TIMEOUT=${PP_TIMEOUT}
WORKING_DIR=\"${PP_WORKING_DIRECTORY}\"
PARALLEL=${PP_PARALLEL}

# Process tracking
declare -a PIDS=()
declare -a NAMES=()
declare -a EXIT_CODES=()

# Function to cleanup background processes
cleanup() {
    echo \"Cleaning up background processes...\"
    for pid in \"\${PIDS[@]}\"; do
        if kill -0 \$pid 2>/dev/null; then
            echo \"Killing process \$pid\"
            kill -TERM \$pid 2>/dev/null || true
            sleep 1
            kill -KILL \$pid 2>/dev/null || true
        fi
    done
}

# Set up signal handlers for cleanup
trap cleanup EXIT INT TERM

echo \"Starting parallel process test: \$TEST_NAME\"
echo \"Working directory: \$WORKING_DIR\"
echo \"Timeout: \$TIMEOUT seconds\"

cd \"\$WORKING_DIR\"

# Environment variables
")
  
  # Add environment variables
  if(PP_ENVIRONMENT)
    foreach(env_var ${PP_ENVIRONMENT})
      set(SCRIPT_CONTENT "${SCRIPT_CONTENT}export ${env_var}\n")
    endforeach()
  endif()
  
  # Add process launching logic
  set(PROCESS_INDEX 0)
  foreach(process_spec ${PROCESSES})
    # Split process spec
    string(REPLACE "|" ";" process_parts "${process_spec}")
    list(GET process_parts 0 executable)
    list(LENGTH process_parts parts_count)
    if(parts_count GREATER 1)
      list(GET process_parts 1 arguments)
    else()
      set(arguments "")
    endif()
    
    math(EXPR PROCESS_INDEX "${PROCESS_INDEX} + 1")
    
    if(PP_PARALLEL)
      set(SCRIPT_CONTENT "${SCRIPT_CONTENT}
# Start process ${PROCESS_INDEX} in background
echo \"Starting process ${PROCESS_INDEX}: ${executable} ${arguments}\"
PROCESS_ROLE=\$PROCESS_${PROCESS_INDEX}_ROLE SIMULATED_IP=\$PROCESS_${PROCESS_INDEX}_IP ${executable} ${arguments} &
PID_${PROCESS_INDEX}=\$!
PIDS+=(\$PID_${PROCESS_INDEX})
NAMES+=(\"process_${PROCESS_INDEX}\")
echo \"Process ${PROCESS_INDEX} started with PID \$PID_${PROCESS_INDEX}\"
")
    else()
      set(SCRIPT_CONTENT "${SCRIPT_CONTENT}
# Start process ${PROCESS_INDEX} sequentially  
echo \"Starting process ${PROCESS_INDEX}: ${executable} ${arguments}\"
PROCESS_ROLE=\$PROCESS_${PROCESS_INDEX}_ROLE SIMULATED_IP=\$PROCESS_${PROCESS_INDEX}_IP ${executable} ${arguments}
EXIT_CODE_${PROCESS_INDEX}=\$?
EXIT_CODES+=(\$EXIT_CODE_${PROCESS_INDEX})
NAMES+=(\"process_${PROCESS_INDEX}\")
echo \"Process ${PROCESS_INDEX} completed with exit code \$EXIT_CODE_${PROCESS_INDEX}\"
")
    endif()
  endforeach()
  
  if(PP_PARALLEL)
    # Add parallel wait logic
    set(SCRIPT_CONTENT "${SCRIPT_CONTENT}
# Wait for all processes with timeout
echo \"Waiting for \${#PIDS[@]} processes to complete...\"

# Function to wait for process with timeout
wait_with_timeout() {
    local pid=\$1
    local timeout=\$2
    local count=0
    
    while [ \$count -lt \$timeout ]; do
        if ! kill -0 \$pid 2>/dev/null; then
            # Process has finished
            wait \$pid 2>/dev/null || true
            return \$?
        fi
        sleep 1
        count=\$((count + 1))
    done
    
    # Timeout exceeded
    echo \"Process \$pid timed out after \$timeout seconds\"
    kill -TERM \$pid 2>/dev/null || true
    sleep 2
    kill -KILL \$pid 2>/dev/null || true
    return 124  # Standard timeout exit code
}

# Wait for ALL processes first, then check exit codes
for i in \"\${!PIDS[@]}\"; do
    pid=\${PIDS[\$i]}
    name=\${NAMES[\$i]}
    
    echo \"Waiting for \$name (PID \$pid)...\"
    wait_with_timeout \$pid \$TIMEOUT
    exit_code=\$?
    EXIT_CODES+=(\$exit_code)
done

# Now report results
for i in \"\${!EXIT_CODES[@]}\"; do
    name=\${NAMES[\$i]}
    exit_code=\${EXIT_CODES[\$i]}
    
    if [ \$exit_code -eq 0 ]; then
        echo \"\$name completed successfully\"
    else
        echo \"\$name failed with exit code \$exit_code\"
    fi
done
")
  endif()
  
  # Add result checking
  set(SCRIPT_CONTENT "${SCRIPT_CONTENT}
# Check results
echo \"Checking results...\"
ALL_SUCCESS=true
FAILED_PROCESSES=()

for i in \"\${!EXIT_CODES[@]}\"; do
    name=\${NAMES[\$i]}
    exit_code=\${EXIT_CODES[\$i]}
    
    if [ \$exit_code -ne 0 ]; then
        ALL_SUCCESS=false
        FAILED_PROCESSES+=(\"\$name (exit code \$exit_code)\")
    fi
done

if [ \"\$ALL_SUCCESS\" = true ]; then
    echo \"SUCCESS: All \${#EXIT_CODES[@]} processes completed successfully\"
    exit 0
else
    echo \"FAILURE: The following processes failed:\"
    for failed in \"\${FAILED_PROCESSES[@]}\"; do
        echo \"  - \$failed\"
    done
    exit 1
fi
")
  
  # Write the script
  file(GENERATE OUTPUT "${SCRIPT_PATH}" CONTENT "${SCRIPT_CONTENT}")
  
  # Make script executable
  if(CMAKE_HOST_UNIX)
    add_custom_command(
      OUTPUT "${SCRIPT_PATH}.executable"
      COMMAND chmod +x "${SCRIPT_PATH}"
      COMMAND touch "${SCRIPT_PATH}.executable"
      DEPENDS "${SCRIPT_PATH}"
      COMMENT "Making ${PP_NAME} script executable"
    )
    
    add_custom_target("${PP_NAME}_make_executable"
      DEPENDS "${SCRIPT_PATH}.executable"
    )
  endif()
  
  # Add the CTest test
  add_test(
    NAME ${PP_NAME}
    COMMAND ${PP_SHELL} "${SCRIPT_PATH}"
    WORKING_DIRECTORY "${PP_WORKING_DIRECTORY}"
  )
  
  # Set test properties
  set_tests_properties(${PP_NAME} PROPERTIES
    TIMEOUT ${PP_TIMEOUT}
    LABELS "parallel;multiprocess"
  )
  
  # If targets were specified, add dependencies
  foreach(target_spec ${PP_TARGETS})
    string(FIND "${target_spec}" " " first_space)
    if(first_space GREATER -1)
      string(SUBSTRING "${target_spec}" 0 ${first_space} target_name)
    else()
      set(target_name "${target_spec}")
    endif()
    
    if(TARGET ${target_name})
      set_tests_properties(${PP_NAME} PROPERTIES
        FIXTURES_REQUIRED "${target_name}_built"
      )
    endif()
  endforeach()
  
  # Note: We can't add dependencies here because the test isn't a target
  # The script executable dependency is handled through the custom target
  
  message(STATUS "Added parallel process test: ${PP_NAME}")
endfunction()

# Convenience function for network-based multiprocess tests
function(ut_add_network_parallel_test)
  set(options SEQUENTIAL)
  set(oneValueArgs NAME PARTICIPANTS EXECUTABLE TIMEOUT MULTICAST_GROUP MULTICAST_PORT)
  set(multiValueArgs ADDITIONAL_ENV)
  
  cmake_parse_arguments(NP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  
  if(NOT NP_NAME OR NOT NP_PARTICIPANTS OR NOT NP_EXECUTABLE)
    message(FATAL_ERROR "ut_add_network_parallel_test: NAME, PARTICIPANTS, and EXECUTABLE are required")
  endif()
  
  # Set defaults
  if(NOT NP_TIMEOUT)
    set(NP_TIMEOUT 30)
  endif()
  
  if(NOT NP_MULTICAST_GROUP)
    set(NP_MULTICAST_GROUP "239.255.0.1")
  endif()
  
  if(NOT NP_MULTICAST_PORT)
    set(NP_MULTICAST_PORT 12345)
  endif()
  
  # Build simple targets list 
  set(TARGET_LIST "")
  foreach(i RANGE 1 ${NP_PARTICIPANTS})
    list(APPEND TARGET_LIST "${NP_EXECUTABLE}")
  endforeach()
  
  # Build environment variables and per-process role/IP assignments
  set(ENV_VARS 
    "MULTICAST_GROUP=${NP_MULTICAST_GROUP}"
    "MULTICAST_PORT=${NP_MULTICAST_PORT}"
    "PARTICIPANT_COUNT=${NP_PARTICIPANTS}"
  )
  
  # Store role and IP mapping for later use in script generation
  foreach(i RANGE 1 ${NP_PARTICIPANTS})
    if(i EQUAL 1)
      set(ROLE "server")
    else()
      set(ROLE "client${i}")
    endif()
    
    # Use loopback IPs for native testing (127.0.0.x)
    math(EXPR IP_SUFFIX "${i} + 1")
    set(IP "127.0.0.${IP_SUFFIX}")
    
    list(APPEND ENV_VARS "PROCESS_${i}_ROLE=${ROLE}")
    list(APPEND ENV_VARS "PROCESS_${i}_IP=${IP}")
  endforeach()
  
  if(NP_ADDITIONAL_ENV)
    list(APPEND ENV_VARS ${NP_ADDITIONAL_ENV})
  endif()
  
  # Create the test
  if(NP_SEQUENTIAL)
    ut_add_parallel_process_test(
      NAME ${NP_NAME}
      TARGETS ${TARGET_LIST}
      SEQUENTIAL
      TIMEOUT ${NP_TIMEOUT}
      ENVIRONMENT ${ENV_VARS}
    )
  else()
    ut_add_parallel_process_test(
      NAME ${NP_NAME}
      TARGETS ${TARGET_LIST}
      PARALLEL
      TIMEOUT ${NP_TIMEOUT}
      ENVIRONMENT ${ENV_VARS}
    )
  endif()
endfunction()

# Add custom target for running parallel tests with optimal concurrency
if(NOT TARGET multiprocess_tests)
  include(ProcessorCount)
  ProcessorCount(N)
  if(NOT N EQUAL 0)
    set(PARALLEL_JOBS ${N})
  else()
    set(PARALLEL_JOBS 4)
  endif()
  
  add_custom_target(multiprocess_tests
    COMMAND ${CMAKE_CTEST_COMMAND} -L "parallel" -j${PARALLEL_JOBS} --output-on-failure
    COMMENT "Running parallel process tests with ${PARALLEL_JOBS} concurrent jobs"
    USES_TERMINAL
  )
endif()